### ISSUE TITLE
nameAt Regex is somewhat off

### ISSUE THREAD

**Issue by silkentrance** [npm/npm-package-arg#12]
The regular expression for checking whether it is a version string prefixed by an '@' and optional other text is somewhat off

```
/^(@([^/]+?)[/])?([^/]+?)@/
```

While this works for strings like

```
foo.git@1.2.3
foo.git:4@1.2.3
@foo.git@1.2.3
```

and so on, it will fail on

```
git@github.com:foo/bar.git@1.2.3      -> [git@,,git]
github.com:foo/bar.git@1.2.3    -> null
github.com/foo/bar.git@1.2.3    -> null
```

Which I think is a valid use case for this.

Especially the part where it reads `^(@(...` is IMO erroneous and should be reworked.

**Comment by silkentrance** [comment]
Would'nt a simple substr(lastIndexOf('@')) suffice?

**Comment by iarna** [comment]
silkentrance: None of the specs you gave are valid.

Specs are this:
`packagename@source`

Either are optional, but not both, obviously.

Those breakdown such that `packagename` can be a plain name, or it can include a scope, `packagename = @scope/project`

The source can be many things, a version, a dist-tag, a semver range, a file or directory, a URL, or, as you used, a git remote address.

Now because the git remote address is part of the source, it can't include a version. What you *can* do is link to a git tag, you do that by adding "#tagname" to the end of your git address, so if you tagged the way `npm version` does. So all of the following would be valid:

```
git://github.com:foo/bar.git#v1.2.3
ssh://git@github.com/foo/bar.git#v1.2.3
git+http://github.com/foo/bar.git#v1.2.3
```
Plus, because we like paving cow paths, you can use a shortcut for github in particular:
```
foo/bar#v1.2.3
```

**Comment by iarna** [comment]
Closing this as there's no issue. (The regexps are kind of hinky, but they aren't causing problems as far as I can see.)
